// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
)

type Querier interface {
	CreateTransform(ctx context.Context, arg CreateTransformParams) (Transform, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DecUrlCount(ctx context.Context, username string) (User, error)
	DeleteTransform(ctx context.Context, id int64) error
	GetTransform(ctx context.Context, id int64) (Transform, error)
	GetTransformForUpdate(ctx context.Context, id int64) (Transform, error)
	GetUser(ctx context.Context, username string) (User, error)
	IncUrlCount(ctx context.Context, username string) (User, error)
	ListTransforms(ctx context.Context, arg ListTransformsParams) ([]Transform, error)
	UpdateTransform(ctx context.Context, arg UpdateTransformParams) (Transform, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
